#!/bin/sh

set -e

rm -rf xemacs
mkdir -p xemacs

sed 's/^TAG=.*/TAG=${TAG:-_SBo}/' xemacs.SlackBuild > xemacs/xemacs.SlackBuild
sed -i 's/^OUTPUT=.*/OUTPUT=${OUTPUT:-\/tmp}/' xemacs/xemacs.SlackBuild
sed -i 's/^if false; then # SlackBuilds/if true; then/' xemacs/xemacs.SlackBuild
chmod +x xemacs/xemacs.SlackBuild

cp README xemacs
cp *.patch xemacs
cp slack-desc* xemacs

VERSION=`grep "^VERSION=" xemacs.SlackBuild | cut -d= -f2`
echo "Version '$VERSION'"

MD5SUM=`md5sum xemacs-$VERSION.tar.bz2 | cut -d" " -f1`

cat << EOF > xemacs/xemacs.info
PRGNAM="xemacs"
VERSION="$VERSION"
HOMEPAGE="http://xemacs.org/"
DOWNLOAD="http://ftp.xemacs.org/pub/xemacs/stable/xemacs-$VERSION.tar.bz2"
MD5SUM="$MD5SUM"
MAINTAINER="Sean MacLennan"
EMAIL="xemacs@seanm.ca"
EOF

tar zcf slackbuilds.tar.gz xemacs
