#!/bin/sh

# Edit /usr/share/applications/emacs.desktop:
# change Exec=emacs to Exec=2emacs
# Edit ~/.local/share/applications/mimeapps.list

[ -n "$1" ] || { echo "2emacs what?"; exit 1; }

FILE=`echo $1 | cut -d: -f1`
N=`echo $1 | awk -F: '{print $2}'`

if [ "$N" -eq "$N" ] 2>/dev/null; then
    ARG="+$N"
else
    unset ARG
fi

# dash and ksh do not have $UID
[ -z "$UID" ] && UID=$(id -u)

if [ -S /tmp/emacs$UID/server ]; then
    emacsclient -n $ARG $FILE
else
    emacs $ARG $FILE &
fi
