#!/bin/sh

# Edit /usr/share/applications/emacs.desktop:
# change Exec=emacs to Exec=2emacs
# Edit ~/.local/share/applications/mimeapps.list

[ -n "$1" ] || { echo "2emacs what?"; exit 1; }

FILE=$1
if [ "$1" = "-name" -o "$1" = "-n" ]; then
    [ -n "$2" ] || { echo "2emacs -name what?"; exit 1; }
    FILE=`find -name $2 | head -n1`
    [ -n "$FILE" ] || { echo "no file found"; exit 1; }
fi

FNAME=`echo $FILE | cut -d: -f1`
N=`echo $FILE | awk -F: '{print $2}'`

if [ -n "$N" -a "$N" -eq "$N" ] 2>/dev/null; then
    ARG="+$N"
else
    unset ARG
fi

# Test /tmp/emacs$UID first since you might be running an older Emacs but
# have XDG_RUNTIME_DIR set.

# dash and ksh do not have $UID
[ -z "$UID" ] && UID=$(id -u)
if [ -S /tmp/emacs$UID/server ]; then
    emacsclient -n $ARG $FNAME
elif [ -S "$XDG_RUNTIME_DIR/emacs/server" ]; then
    # Added in 27.1
    emacsclient -n $ARG $FNAME
else
    emacs $ARG $FNAME &
fi
